import type { NextPage } from "next";
import { useEffect } from "react";
import EnglishLayout from "../layouts/EnglishLayout";
import Image from "next/image";
import Head from "next/head";

declare const window: Window &
  typeof globalThis & {
    jQuery: any;
    $: any;
  };

// import styles from "../styles/Services501c3.module.css";
const placeholder =
  "https://s3.amazonaws.com/media.startchurch.com/Media/features/temp_image.jpg";

const Services501c3: NextPage = () => {
  useEffect(() => {
    if (typeof window !== "undefined" && typeof window.jQuery === "undefined") {
      window.jQuery = window.$ = require("../public/js/jquery.min.js");
    }
    require("../public/js/jquery.easytabs.js");
    window.$(".tabs.tabs-2-big-top").easytabs({
      animationSpeed: 200,
      updateHash: false,
    });
  });
  return (
    <EnglishLayout>
      <Head>
        <title>How to get 501(c)(3) Status | StartCHURCH</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="block-content">
        <section className="white-bg">
          <div className="container inner-top inner-bottom-sm">
            <div className="row">
              <div className="col-md-8 col-sm-9 text-center center-block">
                <header>
                  <div
                    className="h1 light-color"
                    style={{ background: "#5cb85c", padding: 15 }}
                  >
                    Easy. Affordable. Trusted.
                  </div>
                  <p>
                    It has never been easier to get started! The StartRIGHT
                    Service has helped thousands of churches obtain 501(c)(3)
                    tax-exempt status and establish a strong foundation that
                    protects what God has given them to lead. This proven system
                    results in maximized protection while building strength on
                    which to grow.
                  </p>
                </header>
              </div>
            </div>
            <div className="row inner-top-sm">
              <div className="col-md-1">
                <div className="icon pull-right">
                  <i className="icon-sc-check-square-o icn"></i>
                </div>
              </div>
              <div className="col-md-3 inner-bottom-xs">
                <h2>Easy</h2>
                <p>
                  Starting your church has never been easier. We listen to your
                  vision and fill out all of the complicated paper work for you
                  to help ensure that you are protecting what God has given you
                  to lead. It allows you to continue to pursue your vision.
                </p>
                <ul className="circled">
                  <li>No IRS forms to fill out.</li>
                  <li>No IRS agents to talk to.</li>
                  <li>No complicated paperwork.</li>
                </ul>
              </div>
              <div className="col-md-1">
                <div className="icon pull-right">
                  <i className="icon-sc-usd icn"></i>
                </div>
              </div>
              <div className="col-md-3 inner-bottom-xs">
                <h2>Affordable</h2>
                <p>
                  We understand that starting a church is a giant leap of faith.
                  We also understand that taking that leap of faith costs money.
                  The StartRIGHT Service does not require large legal fees like
                  most companies do.
                </p>
                <ul className="circled">
                  <li>Easy monthly payments.</li>
                  <li>Get started right away.</li>
                  <li>Designed with church planters in mind.</li>
                </ul>
              </div>
              <div className="col-md-1">
                <div className="icon pull-right">
                  <i className="icon-sc-thumbs-o-up icn"></i>
                </div>
              </div>
              <div className="col-md-3 inner-bottom-xs">
                <h2>Trusted</h2>
                <p>
                  Over the past 20 years, our team of attorneys, CPAs, and
                  church planting specialists has helped thousands of churches
                  establish a legal foundation that has protected their vision.
                  Join the thousands who have trusted StartCHURCH.
                </p>
                <ul className="circled">
                  <li>Thousands of churches started.</li>
                  <li>100% approval rate.</li>
                  <li>Money-back guarantee if not approved.</li>
                </ul>
              </div>
            </div>
          </div>
        </section>

        <section
          className="img-bg img-bg-soft tint-bg lazy-bg"
          data-src="https://s3.amazonaws.com/assets-startchurch-stage/REB+assets/images/banners/option_4.jpg"
          style={{ backgroundPosition: "35% 30% !important" }}
        >
          <div className="container inner-sm">
            <div className="row">
              <div className="col-md-8 col-sm-9 text-left pull-right">
                <header>
                  <div className="feature-box darker">
                    <h1>Obtain 501(c)(3) Tax-Exempt Status</h1>
                    <p>
                      For years now, obtaining the 501(c)(3) tax-exempt status
                      has been an intimidating and challenging process to
                      churches and ministries - UNTIL NOW! With the StartRIGHT
                      Service, it has never been easier to obtain tax-exempt
                      status. There are many benefits to obtaining 501(c)(3)
                      status.
                    </p>
                    <ul className="circled">
                      <li>Exemption from federal income tax</li>
                      <li>Tax-deductible contributions</li>
                      <li>Exemption from federal unemployment tax</li>
                      <li>AND MUCH MORE!</li>
                    </ul>
                  </div>
                </header>
              </div>
            </div>
          </div>
        </section>

        <section>
          <div className="container inner">
            <div className="row text-center">
              <div className="col-md-8 col-sm-9 center-block">
                <header>
                  <div className="h1">The StartRIGHT Service Does it All.</div>
                  <p>
                    With the StartRIGHT Service, you can rest assured that you,
                    the vision God planted in your heart, and the members of
                    your church are protected. We come alongside you and take
                    care of everything. You can get back to pursuing your
                    vision, while we do all of the heavy lifting. Speaking of
                    heavy lifting, here is what some of that entails.
                  </p>
                </header>
              </div>
            </div>
            <div className="row inner-top-sm text-center">
              <div className="col-md-4 col-sm-6 inner-bottom-xs">
                <div className="icon">
                  <i className="icon-sc-building icn lg"></i>
                </div>
                <h2>Incorporation*</h2>
                <p>
                  With the StartRIGHT Service, our specialists will help you
                  develop articles of incorporation* that will give you a strong
                  legal shield, ensuring your limited legal liability, and will
                  protect you and your members. You can create articles of
                  incorporation* that reflect your vision and mission. Getting
                  incorporated also gives you the ability to license and ordain
                  ministers of the Gospel and serves as the legal birth of your
                  organization.{" "}
                </p>
              </div>
              <div className="col-md-4 col-sm-6 inner-bottom-xs">
                <div className="icon">
                  <i className="icon-sc-university icn lg"></i>
                </div>
                <h2>FEIN</h2>
                <p>
                  We obtain your personal Federal Employer Identification
                  Number, and provide you with all of the information you need
                  to open a church bank account, enabling you to take
                  tax-deductible tithes and offerings. This number is used to
                  identify your corporation and is needed for business and
                  federal purposes. This number may also be known as a Tax ID
                  Number.
                </p>
              </div>
              <div className="clearfix visible-sm-block"></div>
              <div className="col-md-4 col-sm-6 inner-bottom-xs">
                <div className="icon">
                  <i className="icon-sc-gavel icn lg"></i>
                </div>
                <h2>Bylaws*</h2>
                <p>
                  Other than the Scriptures, the bylaws* are the most important
                  document in your church. The StartRIGHT Service empowers you
                  to select the bylaws* that protect your vision, your ministry,
                  and your members, adopting the governmental structure that
                  reflects your ministry structure and allowing the
                  pastor&apos;s vision to be kept clear.
                </p>
              </div>
              <div className="clearfix visible-md-block visible-lg-block"></div>
              <div className="col-md-4 col-sm-6 inner-bottom-xs">
                <div className="icon">
                  <i className="icon-doc-1 icn lg"></i>
                </div>
                <h2>Policies</h2>
                <p>
                  Many church leaders feel a desire to craft supporting policies
                  but are overwhelmed at the process of developing the correct
                  wording that will accurately develop such policies. With the
                  StartRIGHT Service, we assist you in developing essential
                  policies that help establish and protect your board of
                  directors and those helping lead your ministry.
                </p>
              </div>
              <div className="clearfix visible-sm-block"></div>
              <div className="col-md-4 col-sm-6 inner-bottom-xs">
                <div className="icon">
                  <i className="icon-money icn lg"></i>
                </div>
                <h2>Tax-Exempt Status</h2>
                <p>
                  We understand that planting a church can be a difficult
                  journey, which is why we have made it very simple, secure, and
                  affordable for every church to obtain tax-exempt status. We
                  fill out the 501(c)(3) application with you, using the
                  information that you give us, and we guarantee that you will
                  be approved for your 501(c)(3) tax-exempt status or your money
                  back.
                </p>
              </div>
              <div className="col-md-4 col-sm-6 inner-bottom-xs">
                <div className="icon">
                  <i className="icon-users-1 icn lg"></i>
                </div>
                <h2>Ordination</h2>
                <p>
                  Many ministers believe that they are only able to plant a
                  church if they have either been ordained or licensed as
                  ministers of the gospel. However, after establishing a church
                  on a solid legal foundation, you can become ordained right
                  through the very church you started. We provide all of the
                  needed paperwork that empowers your ministry to ordain
                  ministers, including the founder.
                </p>
              </div>
            </div>
          </div>
        </section>

        <section className="tint-bg" style={{ backgroundColor: "#5cb85c" }}>
          <div className="container inner-sm">
            <div className="row">
              <div className="col-sm-12 text-center">
                <div className="h1" style={{ marginBottom: 10 }}>
                  Schedule a call and start taking your vision forward!
                </div>
                <div className="h1" style={{ marginBottom: 10, fontSize: 40 }}>
                  <a
                    href="{{ path('sac')}}"
                    target="_blank"
                    className="btn btn-orange btn-large"
                    style={{ backgroundColor: "#fd5604 !important" }}
                  >
                    SCHEDULE A CALL
                  </a>
                </div>
              </div>
            </div>
          </div>
        </section>
        <section id="video-section-testimony" className="light-bg">
          <div className="container inner-sm">
            <div className="row">
              <div className="col-sm-9 center-block text-center">
                <header>
                  <div className="h1">
                    Hear what pastors are saying about the StartRIGHT Service.
                  </div>
                </header>
                video goes here
                {/* {{  {'id': 'v56f7h54dn', 'image': 'https://embedwistia-a.akamaihd.net/deliveries/1feedac60705fe2f3fd7c513a005e409.webp?image_crop_resized=640x360' } | WistiaVideo | raw }} */}
                <div className="col-xs-10 outer-top-xs center-block text-center">
                  <header>
                    <p>
                      <i>
                        &quot;We want to encourage you. Are you a church
                        planter? Are you starting a ministry? Are you ready to
                        answer the call of God on your life? Let StartCHURCH
                        help you like they have helped us.&quot;
                      </i>
                    </p>
                    <p style={{ color: "#6bc04b" }}>
                      <i>
                        <strong>
                          - Pastor Moses Anderson, Communion House.
                        </strong>
                      </i>
                    </p>
                  </header>
                </div>
              </div>
            </div>
          </div>
        </section>

        <section style={{ backgroundColor: "#74b566" }}>
          <div className="container inner-sm">
            <div className="row">
              <div className="col-md-7 text-left light-color">
                <div className="col-md-5 text-center visible-sm visible-xs inner-bottom-xs">
                  <a href="{{path('products')}}">
                    <Image
                      src="https://s3.amazonaws.com/marketing2019-startchurch/startright/group_suites.webp"
                      width="450"
                      height="199"
                      // style={{ width: "100%", maxWidth: 450 }}
                      alt="Powerful, Cloud-Based Software Tools Image"
                    />
                    {/* <img
                      src={placeholder}
                      data-src=""
                      
                    /> */}
                  </a>
                </div>
                <div
                  className="h1 light-color"
                  style={{ marginBottom: 10, fontSize: 32 }}
                >
                  Powerful, Cloud-Based Software Tools
                </div>
                <p>
                  The StartRIGHT Service is a bundle of software and services
                  you can use to protect what God has called you to lead. With
                  the purchase of the StartRIGHT Service, you will have access
                  to five powerful tools: Launch Suite, Minutes Suite, Policies
                  Suite, Tax Suite, and Exemption Suite. In addition to this
                  software, you can use our FREE clerical services that will put
                  a specialist to work for you in filling out the paperwork as
                  you direct. This really is America&apos;s #1 church planting
                  service!
                </p>
                <p>
                  <a
                    href="{{path('products')}}"
                    style={{ marginLeft: 0 }}
                    className="btn btn-primary "
                  >
                    LEARN ABOUT OUR SOFTWARE
                  </a>
                </p>
              </div>
              <div className="col-md-5 text-center hidden-sm hidden-xs inner-top-xs">
                <a href="{{path('products')}}">
                  <Image
                    src="https://s3.amazonaws.com/marketing2019-startchurch/startright/group_suites.webp"
                    width="450"
                    height="199"
                    // style={{ width: "100%", maxWidth: 450 }}
                    alt="Powerful, Cloud-Based Software Tools Image"
                  />
                </a>
              </div>
            </div>
          </div>
        </section>

        <section
          className="img-bg img-bg-soft tint-bg lazy-bg"
          data-src="https://s3.amazonaws.com/assets-startchurch-stage/REB+assets/images/banners/option_3.jpg"
          style={{ backgroundPosition: "23% 10% !important" }}
        >
          <div className="container inner-sm">
            <div className="row">
              <div className="col-md-8 col-sm-9 text-left pull-right">
                <header>
                  <div className="feature-box darker">
                    <div className="h1">Become Legally Ordained</div>
                    <p>
                      A core part of the StartRIGHT Service is the ability to
                      license and ordain ministers of the gospel, starting with
                      the senior pastor. With this service, you can be legally
                      ordained through your own ministry, with the ability to do
                      weddings, visit prisons, save on parking at hospitals, and
                      take special tax deductions only available to legally
                      ordained pastors. God has called you; let the StartRIGHT
                      Service give you the legal ordination that comes with that
                      call.
                    </p>
                  </div>
                </header>
              </div>
            </div>
          </div>
        </section>
        <section className="tint-bg" style={{ backgroundColor: "#fa5821" }}>
          <div className="container inner-sm">
            <div className="row">
              <div className="col-sm-12 text-center">
                <div className="h1" style={{ marginBottom: 10 }}>
                  Call today to speak to a church planting specialist
                </div>
                <div className="h1" style={{ marginBottom: 0, fontSize: 40 }}>
                  <span className="rTapNumber227338">XXXXXX</span>
                </div>
              </div>
            </div>
          </div>
        </section>

        <section className="light-background light-bg">
          <div className="container inner-top">
            <div className="row">
              <div className="col-md-8 col-sm-9 text-center center-block">
                <header>
                  <div className="h1">
                    A Church Planting Service You Can Trust
                  </div>
                  <p>
                    With our 100% IRS approval guarantee, you will feel
                    confident knowing that you are doing business with the
                    industry-leading church planting organization that cares
                    about the success of your church, ministry, or nonprofit
                    outreach. Our team of attorneys, CPAs, and church planting
                    specialists has helped thousands of churches and ministries
                    establish a legal foundation that has protected the church,
                    its members, and the vision of the pastor.
                  </p>
                </header>
              </div>
            </div>

            <div className="row visible-xs inner-sm inner-top-xs">
              <div
                className="col-md-8 col-xs-12 aos-init aos animate center-block"
                data-aos="fade-up"
                style={{ maxWidth: 400 }}
              >
                <div id="two-step-accordion" className="panel-group">
                  <div className="panel panel-default">
                    <div className="panel-heading">
                      <h4 className="panel-title">
                        <a
                          className="panel-toggle collapsed"
                          href="#two-step-content1"
                          data-toggle="collapse"
                        >
                          <span>501(c)(3) Made Easy!</span>
                        </a>
                      </h4>
                    </div>
                    <div
                      id="two-step-content1"
                      className="panel-collapse collapse"
                      data-parent="#two-step-accordion"
                    >
                      <div className="panel-body">
                        <div
                          className="lazy-bg"
                          data-src="https://s3.amazonaws.com/assets-startchurch-stage/REB+assets/images/website+2.1/startright/str_box_1.jpg"
                        ></div>
                        <p>
                          In the StartRIGHT Service, we follow a deep
                          conversational approach to understanding the vision
                          and mission that God has given you, in order to secure
                          501(c)(3) status for your church. This gives pastors
                          and leaders confidence, knowing that they are building
                          the dream God has given them.
                        </p>
                      </div>
                    </div>
                  </div>

                  <div className="panel panel-default">
                    <div className="panel-heading">
                      <h4 className="panel-title">
                        <a
                          className="panel-toggle collapsed"
                          href="#two-step-content2"
                          data-toggle="collapse"
                        >
                          <span>We Represent You!</span>
                        </a>
                      </h4>
                    </div>
                    <div
                      id="two-step-content2"
                      className="panel-collapse collapse"
                      data-parent="#two-step-accordion"
                    >
                      <div className="panel-body">
                        <div
                          style={{
                            backgroundImage:
                              "url('https://s3.amazonaws.com/assets-startchurch-stage/REB+assets/images/website+2.1/startright/str_box_2.webp')",
                          }}
                        ></div>
                        <p>
                          Yes, we are doing the work for you throughout the
                          whole process but you are in control. With your
                          permission, if the IRS has questions about your
                          application, our in-house attorney will communicate
                          with the IRS on your behalf. You are free to focus on
                          your ministry while we focus on your administration
                          planning!
                        </p>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>

            <div
              className="row inner-top-sm hidden-xs"
              style={{ marginBottom: 2 }}
            >
              <div className="col-xs-12">
                <div className="tabs tabs-2-big-top tab-container">
                  <ul className="etabs text-center">
                    <li className="tab">
                      <a href="#tab-1">
                        <h3>501(c)(3) Made Easy!</h3>
                        <p className="text-small">
                          In the StartRIGHT Service, we follow a deep
                          conversational approach to understanding the vision
                          and mission that God has given you, in order to secure
                          501(c)(3) status for your church. This gives pastors
                          and leaders confidence, knowing that they are building
                          the dream God has given them.
                        </p>
                      </a>
                    </li>
                    <li className="tab">
                      <a href="#tab-2">
                        <h3>We Represent You!</h3>
                        <p className="text-small">
                          Yes, we are doing the work for you throughout the
                          whole process but you are in control. With your
                          permission, if the IRS has questions about your
                          application, our in-house attorney will communicate
                          with the IRS on your behalf. You are free to focus on
                          your ministry while we focus on your administration
                          planning!
                        </p>
                      </a>
                    </li>
                  </ul>
                  <div
                    className="panel-container screen-container"
                    style={{ background: "none", marginTop: 0 }}
                  >
                    <div className="tab-content" id="tab-1">
                      <div className="row">
                        <div className="col-md-12">
                          <figure
                            style={{
                              boxShadow: "0 0 30px 10px rgba(73, 73, 73, 0.44)",
                            }}
                          >
                            <Image
                              src="https://s3.amazonaws.com/assets-startchurch-stage/REB+assets/images/website+2.1/startright/str_box_1.jpg"
                              width="800"
                              height="400"
                              layout="responsive"
                              alt="Man Smiling"
                            />
                          </figure>
                        </div>
                      </div>
                    </div>
                    <div className="tab-content" id="tab-2">
                      <div className="row">
                        <div className="col-md-12">
                          <figure
                            style={{
                              boxShadow: "0 0 30px 10px rgba(73, 73, 73, 0.44)",
                            }}
                          >
                            <Image
                              src="https://s3.amazonaws.com/assets-startchurch-stage/REB+assets/images/website+2.1/startright/str_box_2.jpg"
                              width="800"
                              height="400"
                              layout="responsive"
                              alt="handshake"
                            />
                          </figure>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>
    </EnglishLayout>
  );
};

export default Services501c3;
