import type { NextPage } from "next";
import EnglishLayout from "../layouts/EnglishLayout";
import Head from "next/head";
import styles from "../styles/Services501c3.module.css";

const Services501c3: NextPage = () => {
  return (
    <EnglishLayout>
      <Head>
        <title>How to get 501(c)(3) Status | StartCHURCH</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.header}>Header</div>
      <div>
        How to get 501(c)(3) Status | StartCHURCH Everything you need to start
        your church
        <button className="btn btn-primary">Get started now</button>
      </div>
      <div>Protect what God has given you to lead! [video]</div>
      <div>
        Easy. Affordable. Trusted. It has never been easier to get started! The
        StartRIGHT Service has helped thousands of churches obtain 501(c)(3)
        tax-exempt status and establish a strong foundation that protects what
        God has given them to lead. This proven system results in maximized
        protection while building strength on which to grow. Easy
        <p>
          Starting your church has never been easier. We listen to your vision
          and fill out all of the complicated paper work for you to help ensure
          that you are protecting what God has given you to lead. It allows you
          to continue to pursue your vision.
        </p>
        <ul>
          <li>No IRS forms to fill out.</li>
          <li>No IRS agents to talk to.</li>
          <li>No complicated paperwork.</li>
        </ul>
        Affordable
        <p>
          We understand that starting a church is a giant leap of faith. We also
          understand that taking that leap of faith costs money. The StartRIGHT
          Service does not require large legal fees like most companies do.
        </p>
        <ul>
          <li>Easy monthly payments.</li>
          <li>Get started right away.</li>
          <li>Designed with church planters in mind.</li>
        </ul>
        Trusted
        <p>
          Over the past 20 years, our team of attorneys, CPAs, and church
          planting specialists has helped thousands of churches establish a
          legal foundation that has protected their vision. Join the thousands
          who have trusted StartCHURCH.
        </p>
        <ul>
          <li>Thousands of churches started.</li>
          <li>100% approval rate.</li>
          <li>Money-back guarantee if not approved.</li>
        </ul>
      </div>
      <div>
        Obtain 501(c)(3) Tax-Exempt Status
        <p>
          For years now, obtaining the 501(c)(3) tax-exempt status has been an
          intimidating and challenging process to churches and ministries -
          UNTIL NOW! With the StartRIGHT Service, it has never been easier to
          obtain tax-exempt status. There are many benefits to obtaining
          501(c)(3) status.
        </p>
        <li>Exemption from federal income tax</li>
        <li>Tax-deductible contributions</li>
        <li>Exemption from federal unemployment tax</li>
        <li>AND MUCH MORE!</li>
      </div>
      <div>
        The StartRIGHT Service Does it All.
        <p>
          With the StartRIGHT Service, you can rest assured that you, the vision
          God planted in your heart, and the members of your church are
          protected. We come alongside you and take care of everything. You can
          get back to pursuing your vision, while we do all of the heavy
          lifting. Speaking of heavy lifting, here is what some of that entails.
        </p>
        Incorporation* With the StartRIGHT Service, our specialists will help
        you develop articles of incorporation* that will give you a strong legal
        shield, ensuring your limited legal liability, and will protect you and
        your members. You can create articles of incorporation* that reflect
        your vision and mission. Getting incorporated also gives you the ability
        to license and ordain ministers of the Gospel and serves as the legal
        birth of your organization. FEIN
        <p>
          We obtain your personal Federal Employer Identification Number, and
          provide you with all of the information you need to open a church bank
          account, enabling you to take tax-deductible tithes and offerings.
          This number is used to identify your corporation and is needed for
          business and federal purposes. This number may also be known as a Tax
          ID Number.
        </p>
        Bylaws*
        <p>
          Other than the Scriptures, the bylaws* are the most important document
          in your church. The StartRIGHT Service empowers you to select the
          bylaws* that protect your vision, your ministry, and your members,
          adopting the governmental structure that reflects your ministry
          structure and allowing the pastor&apos;s vision to be kept clear.
        </p>
        Policies
        <p>
          Many church leaders feel a desire to craft supporting policies but are
          overwhelmed at the process of developing the correct wording that will
          accurately develop such policies. With the StartRIGHT Service, we
          assist you in developing essential policies that help establish and
          protect your board of directors and those helping lead your ministry.
        </p>
        Tax-Exempt Status
        <p>
          We understand that planting a church can be a difficult journey, which
          is why we have made it very simple, secure, and affordable for every
          church to obtain tax-exempt status. We fill out the 501(c)(3)
          application with you, using the information that you give us, and we
          guarantee that you will be approved for your 501(c)(3) tax-exempt
          status or your money back.
        </p>
        Ordination
        <p>
          Many ministers believe that they are only able to plant a church if
          they have either been ordained or licensed as ministers of the gospel.
          However, after establishing a church on a solid legal foundation, you
          can become ordained right through the very church you started. We
          provide all of the needed paperwork that empowers your ministry to
          ordain ministers, including the founder.
        </p>
      </div>
      <div>
        Schedule a call and start taking your vision forward!
        <button>Schedule a Call</button>
      </div>
      <div>
        Hear what pastors are saying about the StartRIGHT Service. [video]
        <p>
          &ldquo;We want to encourage you. Are you a church planter? Are you
          starting a ministry? Are you ready to answer the call of God on your
          life? Let StartCHURCH help you like they have helped us.&rdquo;
        </p>
        <p>- Pastor Moses Anderson, Communion House.</p>
      </div>
      <div>
        Powerful, Cloud-Based Software Tools The StartRIGHT Service is a bundle
        of software and services you can use to protect what God has called you
        to lead. With the purchase of the StartRIGHT Service, you will have
        access to five powerful tools: Launch Suite, Minutes Suite, Policies
        Suite, Tax Suite, and Exemption Suite. In addition to this software, you
        can use our FREE clerical services that will put a specialist to work
        for you in filling out the paperwork as you direct. This really is
        America&rsquo;s #1 church planting service!
        <button>Learn More About Our Software</button>
      </div>
      <div>
        Become Legally Ordained
        <p>
          A core part of the StartRIGHT Service is the ability to license and
          ordain ministers of the gospel, starting with the senior pastor. With
          this service, you can be legally ordained through your own ministry,
          with the ability to do weddings, visit prisons, save on parking at
          hospitals, and take special tax deductions only available to legally
          ordained pastors. God has called you; let the StartRIGHT Service give
          you the legal ordination that comes with that call.
        </p>
      </div>
      <div>
        Call today to speak to a church planting specialist (833) 827-3061
      </div>
      <div>
        A Church Planting Service You Can Trust
        <p>
          With our 100% IRS approval guarantee, you will feel confident knowing
          that you are doing business with the industry-leading church planting
          organization that cares about the success of your church, ministry, or
          nonprofit outreach. Our team of attorneys, CPAs, and church planting
          specialists has helped thousands of churches and ministries establish
          a legal foundation that has protected the church, its members, and the
          vision of the pastor.
        </p>
        501(C)(3) MADE EASY!
        <p>
          In the StartRIGHT Service, we follow a deep conversational approach to
          understanding the vision and mission that God has given you, in order
          to secure 501(c)(3) status for your church. This gives pastors and
          leaders confidence, knowing that they are building the dream God has
          given them.
        </p>
        We Represent You!
        <p>
          Yes, we are doing the work for you throughout the whole process but
          you are in control. With your permission, if the IRS has questions
          about your application, our in-house attorney will communicate with
          the IRS on your behalf. You are free to focus on your ministry while
          we focus on your administration planning!
        </p>
      </div>
      <div>
        Resources just for you!
        <p>
          At StartCHURCH, we&rsquo;re ministry-minded like you! We care about
          your ministry&rsquo;s success. That’s why we created several free
          resources to encourage you every step of the way as you pursue what
          God has called you to lead.
        </p>
        <p>
          Check out some of our top blogs, ebooks, podcasts, and more for church
          planters just like you!
        </p>
        <button>ACCESS FREE RESOURCES</button>
      </div>
      <div>Footer</div>
    </EnglishLayout>
  );
};

export default Services501c3;
